api:
  name: "lu-sl-sap"
  id: "17817589"
  version: "v1"
  
https:
  path: "/api/${api.version}/*"
  host: "0.0.0.0"
  timeout: "5000" 
  port: "8082"
  #port: "443"
  private:
    port: "8092"
    
sap:
  #baseurl: "http://localhost:3000/"
  baseurl: "https://nameless-eyrie-86329.herokuapp.com/"
  relativepath: "sap/opu/odata/IWFND/CATALOGSERVICE;v=0002/ServiceCollection"
  servicedirectory: "sap/opu/odata/sap"
  
sfdc:
  protocol: "HTTPS"
  host: "lu-sl-sfdc.us-e2.cloudhub.io"
  port: "443"
  basepath: "/api/v1"
  auth:
    username: "test"
    password: "test"