api:
  name: "lu-sl-sap"
  id: "1215395"
  version: "v1"
  
https:
  path: "/api/${api.version}/*"
  host: "0.0.0.0"
  timeout: "5000" 
  port: "8082"
  #port: "443"
  private:
    port: "8092"
    
sap:
  baseurl: "https://nameless-eyrie-86329.herokuapp.com/"
  relativepath: "sap/opu/odata/IWFND/CATALOGSERVICE;v=0002/ServiceCollection"
  servicedirectory: "sap/opu/odata/sap" 